name: build and test

on: [pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    stategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run lint
      